
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Dec  2 2021 17:20:21 IST (Dec  2 2021 11:50:21 UTC)

// Verification Directory fv/demux 

module demux(y, a, din);
  input [1:0] a;
  input din;
  output [3:0] y;
  wire [1:0] a;
  wire din;
  wire [3:0] y;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_3, n_4, n_5, n_7;
  wire n_8;
  TLATX1 \y_reg[3] (.G (n_8), .D (n_4), .Q (y[3]), .QN (UNCONNECTED));
  TLATNX1 \y_reg[2] (.GN (n_7), .D (n_5), .Q (y[2]), .QN
       (UNCONNECTED0));
  AOI21XL g184__8780(.A0 (n_1), .A1 (a[1]), .B0 (n_7), .Y (n_8));
  AND2X1 g180__4296(.A (n_7), .B (din), .Y (y[1]));
  NOR2XL g181__3772(.A (n_3), .B (a[0]), .Y (n_5));
  NOR2BXL g182__1474(.AN (a[0]), .B (n_3), .Y (n_4));
  NOR3XL g183__4547(.A (n_0), .B (a[0]), .C (a[1]), .Y (y[0]));
  NOR2XL g186__9682(.A (n_1), .B (a[1]), .Y (n_7));
  NAND2XL g185__2683(.A (din), .B (a[1]), .Y (n_3));
  INVXL g188(.A (a[0]), .Y (n_1));
  INVXL g187(.A (din), .Y (n_0));
endmodule

